version: '3.5'
services:
  mariadb:
    container_name: mariadb
    image: "mariadb:10.3.9"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=1bd3e0294da19198
      - MYSQL_DATABASE=1bd3e0294da19198
      - MYSQL_PASSWORD=iAlcDxokJhGvpxaK
    volumes:
      - ./mariadb-conf:/etc/mysql/conf.d
      - ./mariadb-initdb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" #mariadb-port

  redis-cache:
    container_name: redis-cache
    image: redis:4.0.11-alpine
    volumes:
      - ./redis-conf/redis_cache.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    sysctls:
      net.core.somaxconn: '511'

  redis-queue:
    container_name: redis-queue
    image: redis:4.0.11-alpine
    volumes:
      - ./redis-conf/redis_queue.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    sysctls:
      net.core.somaxconn: '511'

  redis-socketio:
    container_name: redis-socketio
    image: redis:4.0.11-alpine
    volumes:
      - ./redis-conf/redis_socketio.conf:/etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    sysctls:
      net.core.somaxconn: '511'

  erpnext:
    container_name: erpnext
    image: erpnext:customized
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ROOT_PASSWORD=123
      - ADMIN_PASSWORD=123
      - DB_HOST=mariadb
      - DB_NAME=1bd3e0294da19198
      - DB_PASSWORD=iAlcDxokJhGvpxaK
      - ENCRYPTION_KEY=vZUk5YjEeRdQkGWOFecw2TBFIvmxB7gJ7lZwIE3S9Ds=
      - WORKER=2
    extra_hosts:
      - "site1.local:127.0.0.1"
    stdin_open: true
    tty: true
    links:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
